services:
  api:
    build: .
    container_name: badge-api
    environment:
      PORT: 8000
    ports:
      - '8005:8000'
    volumes:
      - ./src:/app/src
      - ./icons:/app/icons
    env_file:
      - path: ./conf.env
        required: false

